replicaCount: 5

image:
  repository: us-central1-docker.pkg.dev/terraform-project-jad/nodejs/nodejs
  tag: "1.0.0"

service:
  port: 8080


ingress:
  enabled: true
  className: "nginx"
  annotations: 
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: nodejs-prod.jadomars.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
   - secretName: nodejs-prod-tls
     hosts:
       - nodejs-prod.jadomars.com