apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: artemis-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jadomar93/jad-argo.git
    path: application
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../artemis/envs/qa.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: artemis-qa
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
